"""Build the C++ reference model and check it against the Python golden model.

`model/cpp/viterbi_2_1_4.cpp` is the author's original algorithm, now driven by
a file of test vectors instead of one hardcoded word.  This generates the same
exhaustive sweep the RTL is held to, runs it through the C++ program, and
compares every decode against `model/viterbi_ref.py`.

That comparison is what caught the one real bug in the C++: `getFinalLowestState`
initialised its result to the path *metric* rather than a state *index*, which
is invisible on an error-free word (metric 0, state 0) and wrong on every word
carrying an error.  The check exists so that class of bug cannot come back.

    python scripts/check_cpp.py
    python scripts/check_cpp.py --keep     # leave the vector/result files
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

from model import viterbi_ref as ref  # noqa: E402

import vl  # noqa: E402  -- reused only for its Docker plumbing

SRC = REPO / "model" / "cpp" / "viterbi_2_1_4.cpp"
OUT_DIR = REPO / "results" / "cpp"
GREEN, RED, YELLOW, DIM, RESET = (
    "\033[32m", "\033[31m", "\033[33m", "\033[2m", "\033[0m",
)

# The container already used for Verilator carries a C++20 g++, so there is no
# second image to pull just to build a single translation unit.
IMAGE = vl.DEFAULT_IMAGE


EXE_REL = "results/cpp/viterbi_2_1_4"
COMPILE = f"g++ -O2 -std=c++17 -Wall -o {EXE_REL} model/cpp/viterbi_2_1_4.cpp"


def build() -> str | None:
    """Compile the model, natively if a compiler is around, otherwise in Docker.

    Returns the host path of the binary, or None when it only exists inside the
    container and has to be invoked through it.
    """
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    native = shutil.which("g++") or shutil.which("clang++")
    if native:
        exe = REPO / (EXE_REL + (".exe" if sys.platform == "win32" else ""))
        subprocess.run([native, "-O2", "-std=c++17", "-Wall", "-o", str(exe),
                        str(SRC)], check=True, cwd=REPO)
        print(f"  {DIM}built with {Path(native).name}{RESET}")
        return str(exe)

    if not shutil.which("docker"):
        raise SystemExit("need g++/clang++ on PATH, or Docker")

    print(f"  {DIM}no local compiler -- building in {IMAGE}{RESET}")
    vl._sh(vl._docker_prefix(IMAGE) + [COMPILE], quiet=True)
    return None


def run_model(exe: str | None, argv: list[str]) -> subprocess.CompletedProcess:
    """Invoke the built model, wherever it happens to live."""
    if exe:
        return subprocess.run([exe, *argv], cwd=REPO, text=True,
                              capture_output=True)
    cmd = " ".join([EXE_REL, *argv])
    return vl._sh(vl._docker_prefix(IMAGE) + [cmd], check=False, quiet=True)


def write_vectors(path: Path, terminated: bool) -> int:
    """All 128 messages x {clean, every single-bit error position}."""
    encode = ref.encode_terminated if terminated else ref.encode
    cw_bits = ref.TERM_CW_BITS if terminated else ref.CW_BITS

    n = 0
    with path.open("w") as fh:
        fh.write(f"# {'terminated' if terminated else 'unterminated'} "
                 f"(2,1,4) sweep -- generated by scripts/check_cpp.py\n")
        fh.write("# received expected\n")
        for msg in range(128):
            cw = encode(msg)
            for e in range(-1, cw_bits):
                rx = cw if e < 0 else cw ^ (1 << e)
                fh.write(f"{rx:0{cw_bits}b} {msg:07b}\n")
                n += 1
    return n


def run_case(exe: str | None, terminated: bool) -> int:
    label = "terminated" if terminated else "unterminated"
    vectors = OUT_DIR / f"vectors_{label}.txt"
    results = OUT_DIR / f"results_{label}.csv"
    write_vectors(vectors, terminated)

    argv = ["--input", vectors.relative_to(REPO).as_posix(),
            "--output", results.relative_to(REPO).as_posix()]
    if terminated:
        argv.append("--terminate")

    proc = run_model(exe, argv)
    # exit 1 just means some case failed its expectation, which is the answer
    # for the unterminated variant; anything else is a real failure to run.
    if proc.returncode not in (0, 1):
        sys.stderr.write((proc.stdout or "") + (proc.stderr or ""))
        raise SystemExit(f"C++ model failed to run ({label})")

    # Compare against the Python model rather than trusting the C++ self-report.
    decode = ref.decode_terminated if terminated else ref.decode
    mismatches, corrected, total = [], 0, 0
    with results.open() as fh:
        next(fh)                                   # header
        for line in fh:
            _idx, received, decoded, expected, _res = line.strip().split(",")
            total += 1
            want = decode(int(received, 2))
            if int(decoded, 2) != want:
                mismatches.append((received, decoded, f"{want:07b}"))
            corrected += decoded == expected

    rc = 0
    if mismatches:
        print(f"  {RED}FAIL{RESET}  cpp {label}: {len(mismatches)}/{total} cases "
              f"disagree with model/viterbi_ref.py")
        for rx, got, want in mismatches[:5]:
            print(f"          rx={rx}  cpp={got}  model={want}")
        rc = 1
    else:
        print(f"  {GREEN}PASS{RESET}  cpp {label}: agrees with the Python model "
              f"on all {total} cases")

    pct = 100.0 * corrected / total
    errs = total - 128                              # the clean cases
    err_ok = corrected - 128
    if terminated:
        if err_ok == errs:
            print(f"  {GREEN}PASS{RESET}  cpp terminated: every single-bit error "
                  f"corrected ({err_ok}/{errs})")
        else:
            print(f"  {RED}FAIL{RESET}  cpp terminated: {errs - err_ok} single-bit "
                  f"errors uncorrected")
            rc = 1
    else:
        print(f"  {DIM}      cpp unterminated: {err_ok}/{errs} single-bit errors "
              f"corrected ({pct:.1f}% overall) -- capped by the missing tail{RESET}")
    return rc


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--keep", action="store_true",
                    help="keep the generated vector and result files")
    args = ap.parse_args()

    print("Checking the C++ reference model")
    exe = build()
    rc = run_case(exe, terminated=False) + run_case(exe, terminated=True)

    if not args.keep:
        shutil.rmtree(OUT_DIR, ignore_errors=True)
    if rc:
        raise SystemExit(rc)


if __name__ == "__main__":
    main()
